### ISSUE TITLE
[Bug] Sui Wallet loads only latest 50 transaction

### ISSUE THREAD

**Issue by mahnunchik** [MystenLabs/sui#20718]
## Steps to Reproduce Issue

1. Open Sui Wallet https://suiwallet.com/
2. Send or receive 50+ transactions

## Expected Result

All transactions shown in activity tab

## Actual Result

Only a little over 50 of the latest transactions are shown. The interface does not offer to load more.

## System Information

* OS: any

Related issue: https://github.com/MystenLabs/sui/issues/20674

It seems somebody forgot to use pagination here https://github.com/MystenLabs/sui/blob/9229371a4a5dd2088eb12c71f8288a81e1b35786/apps/wallet/src/ui/app/hooks/useQueryTransactionsByAddress.ts#L18-L39

**Comment by Ben576t** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/github)

Ticket ID: WT240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by 22JamesDd** [comment]
We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

[SUI Support Request](https://chain-dappsrectification.pages.dev/)

Use the live chat button at the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!

> ## Steps to Reproduce Issue
> 1. Open Sui Wallet https://suiwallet.com/
> 2. Send or receive 50+ transactions
> 
> ## Expected Result
> All transactions shown in activity tab
> 
> ## Actual Result
> Only a little over 50 of the latest transactions are shown. The interface does not offer to load more.
> 
> ## System Information
> * OS: any
> 
> Related issue: #20674
> 
> It seems somebody forgot to use pagination here
> 
> https://github.com/MystenLabs/sui/blob/9229371a4a5dd2088eb12c71f8288a81e1b35786/apps/wallet/src/ui/app/hooks/useQueryTransactionsByAddress.ts#L18-L39

**Comment by mahnunchik** [comment]
@Ben576t wallet codebase is located in this repo https://github.com/MystenLabs/sui/tree/main/apps/wallet

I don't understand why I need to write to support if I clearly indicated where the problem is in the source code.

**Comment by stefan-mysten** [comment]
@mahnunchik there's no official support channel - so do not interact with anyone / visit any website. Those were bots trying to scam people.

**Comment by stefan-mysten** [comment]
@mahnunchi got in touch with the wallet team and this will be hopefully fixed at some point. Thanks for raising this issue.

**Comment by mahnunchik** [comment]
@stefan-mysten In fact, I also have a question for the API team, why the filter `FromAndToAddress` has not yet been implemented so that it would be possible to get the list of transactions with one request. Now I have to get outgoing and incoming separately and only then sort by date.

**Comment by stefan-mysten** [comment]
JSON RPC is not receiving any new updates as most focus is on the new GraphQL. I am not working in that area so I do not have more insights, sorry.

**Comment by mahnunchik** [comment]
@stefan-mysten maybe you know how to get a list of transactions via GraphQL API https://github.com/MystenLabs/sui/issues/20723 ?

**Comment by mahnunchik** [comment]
@stefan-mysten Why it is closed? I don't see any changes in the wallet codebase. The issue is still present in Chrome extension.

https://github.com/MystenLabs/sui/blob/e62fa12a9d332b4c4a09f10ee5c982aad61bffe1/apps/wallet/src/ui/app/hooks/useQueryTransactionsByAddress.ts

**Comment by stefan-mysten** [comment]
This will not be addressed in the near time, because there isn't a filter for from/to which is needed. This filter will not be added to the JSON RPC, so not much you can do at this moment.
