### ISSUE TITLE
Make links to named anchors work consistently

### ISSUE THREAD

**Issue by yanminmin** [MystenLabs/sui#3756]
i want to learn how to sign a transation from json body.
https://docs.sui.io/devnet/build/json-rpc#2-sign-the-transaction-using-the-sui-signtool
there is an empty link about sign tx  [sing](https://docs.sui.io/devnet/build/json-rpc#2-sign-the-transaction-using-the-sui-signtool)

**Comment by Clay-Mysten** [comment]
@patrickkuo WDYT?

**Comment by patrickkuo** [comment]
Not sure if you are referring to this @yanminmin .

This might be a bug in the doc site
If you browse to the specific section of the doc using url, e.g. https://docs.sui.io/devnet/build/json-rpc#2-sign-the-transaction-using-the-sui-signtool , the "jump to section link" for that section ( in this case : 2-sign-the-transaction-using-the-sui-signtool) will not work until you click on a different link.


https://user-images.githubusercontent.com/1888654/182932617-ef19ca9c-695d-4c95-978b-90a9b157b87d.mov

cc @Jibz1

**Comment by Jibz1** [comment]
@patrickkuo looking into it

**Comment by Clay-Mysten** [comment]
Thanks for looking, @patrickkuo . I can reproduce.

@Jibz1 , please:
1. Go to: https://docs.sui.io/devnet/build/json-rpc#2-sign-the-transaction
2. Click the "[sign the transaction](https://docs.sui.io/devnet/build/json-rpc#2-sign-the-transaction-using-the-sui-signtool)" link.
3. Expect it to load:
https://docs.sui.io/devnet/build/json-rpc#2-sign-the-transaction-using-the-sui-signtool
4. Instead, it does nothing.

May I ask for your help deducing what's going on? Perhaps related to the Devnet intro? Thanks!

**Comment by Jibz1** [comment]
The issue is resolved. @patrickkuo @Clay-Mysten verify.

**Comment by Clay-Mysten** [comment]
> The issue is resolved. @patrickkuo @Clay-Mysten verify.

Strange. When I go to https://docs.sui.io/build/json-rpc#2-sign-the-transaction and click the "[sign the transaction](https://docs.sui.io/build/json-rpc#2-sign-the-transaction-using-the-sui-signtool)" link I still see nothing happen.

**Comment by Jibz1** [comment]
@Clay-Mysten Do a hard refresh.

**Comment by Clay-Mysten** [comment]
I still see the same oddity and think it may be related to the numbered sections. We have all of these on the same page, linking from the latter two to the former:
https://docs.sui.io/build/json-rpc#2-sign-the-transaction-using-the-sui-signtool
https://docs.sui.io/build/json-rpc#2-sign-the-transaction
https://docs.sui.io/build/json-rpc#2-sign-the-transaction-1

FWIW, these anchors work flawlessly for me in GitHub:
https://github.com/MystenLabs/sui/blob/main/doc/src/build/json-rpc.md#2-sign-the-transaction

**Comment by Clay-Mysten** [comment]
Adding @randall-Mysten as an FYI and in case he has ideas.

**Comment by randall-Mysten** [comment]
It looks to me like it is working the same as other links to headings do. It doesn't display the heading as the first line of the page, and instead scrolls down to 4 lines after the heading.
And do you mean to click the Execute link rather than the Sign link? If I open the Sign section I would not expect anything to happen if I click a link to the current section.

**Comment by randall-Mysten** [comment]
It looks off to me that when I click the Sign link it shows the 3, Execute section as first line, and the highlight on the right side is on Sign, but the gray box is over Execute
<img width="1602" alt="image" src="https://user-images.githubusercontent.com/109545725/183145237-ac62b07a-9641-45c7-9500-82918801d7ea.png">

**Comment by randall-Mysten** [comment]
Yeah this seems pretty broken to me

**Comment by Jibz1** [comment]
@randall-Mysten this is fixed.

**Comment by Clay-Mysten** [comment]
LGTM! Thanks, Godwin!
